import { NextResponse } from "next/server";

const mcpServers = [
  {
    id: 1,
    name: "Database MCP Server",
    version: "1.0.0",
    status: "运行中",
    icon: "🗄️",
    category: "数据库",
    uptime: "99.9%",
    connections: 24,
    lastUpdate: "2分钟前",
    latency: "12ms",
    tags: ["推荐"],
  },
  {
    id: 2,
    name: "File System MCP",
    version: "0.9.2",
    status: "运行中",
    icon: "📁",
    category: "文件系统",
    uptime: "98.5%",
    connections: 12,
    lastUpdate: "5分钟前",
    latency: "8ms",
    tags: [],
  },
  {
    id: 3,
    name: "API Gateway MCP",
    version: "2.1.0",
    status: "运行中",
    icon: "🌐",
    category: "网络",
    uptime: "99.5%",
    connections: 48,
    lastUpdate: "1分钟前",
    latency: "25ms",
    tags: ["热门"],
  },
  {
    id: 4,
    name: "Email Service MCP",
    version: "1.2.1",
    status: "已停止",
    icon: "📧",
    category: "通讯",
    uptime: "0%",
    connections: 0,
    lastUpdate: "1天前",
    latency: "-",
    tags: [],
  },
  {
    id: 5,
    name: "Search Engine MCP",
    version: "1.5.0",
    status: "运行中",
    icon: "🔍",
    category: "搜索",
    uptime: "99.8%",
    connections: 36,
    lastUpdate: "3分钟前",
    latency: "15ms",
    tags: ["推荐"],
  },
  {
    id: 6,
    name: "AI Model MCP",
    version: "3.0.0",
    status: "运行中",
    icon: "🤖",
    category: "AI",
    uptime: "99.2%",
    connections: 18,
    lastUpdate: "10分钟前",
    latency: "120ms",
    tags: ["热门", "新上线"],
  },
];

export async function GET() {
  return NextResponse.json({ mcpServers });
}
