import { NextResponse } from "next/server";

const agents = [
  {
    id: 1,
    name: "代码审查助手",
    description: "自动审查代码质量，提供改进建议和最佳实践",
    icon: "🤖",
    category: "开发",
    model: "GPT-4",
    status: "运行中",
    tasks: 1250,
    successRate: "98.5%",
    avgTime: "2.3s",
    tags: ["推荐", "热门"],
    lastRun: "5分钟前",
  },
  {
    id: 2,
    name: "数据分析专家",
    description: "智能分析数据，生成可视化报表和洞察",
    icon: "📊",
    category: "分析",
    model: "Claude-3",
    status: "运行中",
    tasks: 890,
    successRate: "97.2%",
    avgTime: "5.1s",
    tags: ["推荐"],
    lastRun: "15分钟前",
  },
  {
    id: 3,
    name: "客服机器人",
    description: "7x24小时智能客服，自动回答常见问题",
    icon: "💬",
    category: "客服",
    model: "GPT-3.5",
    status: "运行中",
    tasks: 5680,
    successRate: "95.8%",
    avgTime: "1.2s",
    tags: ["热门"],
    lastRun: "1分钟前",
  },
  {
    id: 4,
    name: "文档生成器",
    description: "根据需求自动生成技术文档和API说明",
    icon: "📄",
    category: "文档",
    model: "Claude-3",
    status: "已暂停",
    tasks: 320,
    successRate: "94.1%",
    avgTime: "8.5s",
    tags: [],
    lastRun: "2小时前",
  },
  {
    id: 5,
    name: "测试用例生成",
    description: "自动生成单元测试和集成测试用例",
    icon: "🧪",
    category: "测试",
    model: "GPT-4",
    status: "运行中",
    tasks: 560,
    successRate: "96.3%",
    avgTime: "3.2s",
    tags: ["新上线"],
    lastRun: "30分钟前",
  },
  {
    id: 6,
    name: "翻译助手",
    description: "多语言智能翻译，支持专业领域术语",
    icon: "🌐",
    category: "翻译",
    model: "GPT-4",
    status: "运行中",
    tasks: 2100,
    successRate: "99.1%",
    avgTime: "0.8s",
    tags: ["推荐"],
    lastRun: "3分钟前",
  },
];

export async function GET() {
  return NextResponse.json({ agents });
}
