import { NextResponse } from "next/server";

const knowledgeBases = [
  {
    id: 1,
    name: "产品知识库",
    description: "产品功能、使用指南、FAQ等知识集合",
    icon: "📚",
    category: "产品",
    documents: 256,
    chunks: 12500,
    queries: 8900,
    accuracy: "95.5%",
    tags: ["推荐"],
    updatedAt: "1小时前",
  },
  {
    id: 2,
    name: "技术文档库",
    description: "API文档、架构设计、开发规范等技术资料",
    icon: "🔧",
    category: "技术",
    documents: 180,
    chunks: 8900,
    queries: 5600,
    accuracy: "97.2%",
    tags: ["热门"],
    updatedAt: "3小时前",
  },
  {
    id: 3,
    name: "客服知识库",
    description: "常见问题、解决方案、服务流程等",
    icon: "💬",
    category: "客服",
    documents: 420,
    chunks: 15000,
    queries: 25000,
    accuracy: "94.8%",
    tags: ["推荐", "热门"],
    updatedAt: "30分钟前",
  },
  {
    id: 4,
    name: "行业知识库",
    description: "行业动态、竞品分析、市场研究等",
    icon: "📊",
    category: "市场",
    documents: 95,
    chunks: 4200,
    queries: 1200,
    accuracy: "92.1%",
    tags: [],
    updatedAt: "1天前",
  },
  {
    id: 5,
    name: "内部制度库",
    description: "公司制度、流程规范、培训资料等",
    icon: "📋",
    category: "行政",
    documents: 150,
    chunks: 5600,
    queries: 2800,
    accuracy: "98.5%",
    tags: ["新上线"],
    updatedAt: "2天前",
  },
  {
    id: 6,
    name: "法律合规库",
    description: "法律法规、合规要求、案例分析等",
    icon: "⚖️",
    category: "法务",
    documents: 280,
    chunks: 12000,
    queries: 1500,
    accuracy: "96.3%",
    tags: ["推荐"],
    updatedAt: "5小时前",
  },
];

export async function GET() {
  return NextResponse.json({ knowledgeBases });
}
