import { NextResponse } from "next/server";

const prompts = [
  {
    id: 1,
    name: "代码优化提示词",
    description: "用于优化和重构代码的高质量提示词模板",
    icon: "📝",
    category: "开发",
    uses: 1560,
    rating: 4.9,
    variables: ["language", "code", "goal"],
    tags: ["推荐", "热门"],
    author: "AI团队",
    updatedAt: "2小时前",
  },
  {
    id: 2,
    name: "文章写作模板",
    description: "生成高质量文章的提示词模板，支持多种风格",
    icon: "✍️",
    category: "写作",
    uses: 2340,
    rating: 4.8,
    variables: ["topic", "style", "length"],
    tags: ["热门"],
    author: "内容组",
    updatedAt: "1天前",
  },
  {
    id: 3,
    name: "需求分析模板",
    description: "帮助分析和梳理产品需求的提示词模板",
    icon: "📋",
    category: "产品",
    uses: 890,
    rating: 4.7,
    variables: ["context", "stakeholders", "constraints"],
    tags: ["推荐"],
    author: "产品组",
    updatedAt: "3小时前",
  },
  {
    id: 4,
    name: "SQL生成器",
    description: "根据自然语言描述生成SQL查询语句",
    icon: "🗄️",
    category: "数据库",
    uses: 1200,
    rating: 4.6,
    variables: ["schema", "question", "dialect"],
    tags: [],
    author: "数据组",
    updatedAt: "5小时前",
  },
  {
    id: 5,
    name: "API文档生成",
    description: "自动生成API接口文档的提示词模板",
    icon: "📚",
    category: "文档",
    uses: 670,
    rating: 4.5,
    variables: ["endpoint", "method", "params"],
    tags: ["新上线"],
    author: "API组",
    updatedAt: "1天前",
  },
  {
    id: 6,
    name: "面试问题生成",
    description: "根据岗位要求生成面试问题和评分标准",
    icon: "🎯",
    category: "HR",
    uses: 450,
    rating: 4.8,
    variables: ["position", "level", "skills"],
    tags: ["推荐"],
    author: "HR组",
    updatedAt: "2天前",
  },
];

export async function GET() {
  return NextResponse.json({ prompts });
}
