import { NextResponse } from "next/server";

const skills = [
  {
    id: 1,
    name: "AI 写作助手",
    description: "智能写作助手，帮你快速生成文章、文案、邮件等内容",
    icon: "✍️",
    category: "写作",
    version: "2.1.0",
    status: "已启用",
    users: "12.5万",
    rating: 4.8,
    tags: ["热门", "推荐"],
    lastUsed: "10分钟前",
    apiCalls: 12580,
  },
  {
    id: 2,
    name: "PPT 生成器",
    description: "一键生成专业PPT，支持多种模板和主题",
    icon: "📊",
    category: "办公",
    version: "1.8.5",
    status: "已启用",
    users: "8.2万",
    rating: 4.6,
    tags: ["推荐"],
    lastUsed: "2小时前",
    apiCalls: 8230,
  },
  {
    id: 3,
    name: "AI 绘画",
    description: "文字描述生成精美图片，支持多种风格",
    icon: "🎨",
    category: "创意",
    version: "3.0.2",
    status: "已启用",
    users: "15.3万",
    rating: 4.9,
    tags: ["热门"],
    lastUsed: "5分钟前",
    apiCalls: 18560,
  },
  {
    id: 4,
    name: "智能表格",
    description: "自动处理表格数据，支持公式计算和数据分析",
    icon: "📈",
    category: "办公",
    version: "1.2.0",
    status: "已禁用",
    users: "6.8万",
    rating: 4.5,
    tags: [],
    lastUsed: "3天前",
    apiCalls: 4120,
  },
  {
    id: 5,
    name: "视频生成",
    description: "AI生成短视频，支持多种场景和模板",
    icon: "🎬",
    category: "创意",
    version: "1.5.0",
    status: "已启用",
    users: "5.2万",
    rating: 4.7,
    tags: ["新上线"],
    lastUsed: "1小时前",
    apiCalls: 3580,
  },
  {
    id: 6,
    name: "代码助手",
    description: "智能代码补全、重构和Bug修复",
    icon: "💻",
    category: "开发",
    version: "2.4.1",
    status: "已启用",
    users: "9.1万",
    rating: 4.8,
    tags: ["推荐"],
    lastUsed: "15分钟前",
    apiCalls: 10240,
  },
];

export async function GET() {
  return NextResponse.json({ skills });
}
