import { NextResponse } from "next/server";

const workflows = [
  {
    id: 1,
    name: "自动化测试流程",
    description: "代码提交后自动运行测试、生成报告",
    icon: "🔄",
    category: "DevOps",
    steps: 5,
    status: "运行中",
    runs: 1250,
    successRate: "97.5%",
    avgDuration: "3m 20s",
    tags: ["推荐"],
    lastRun: "10分钟前",
  },
  {
    id: 2,
    name: "内容发布流程",
    description: "文章审核、SEO优化、定时发布的自动化流程",
    icon: "📢",
    category: "内容",
    steps: 8,
    status: "运行中",
    runs: 890,
    successRate: "99.1%",
    avgDuration: "5m 15s",
    tags: ["热门"],
    lastRun: "1小时前",
  },
  {
    id: 3,
    name: "数据同步流程",
    description: "多数据源自动同步和ETL处理",
    icon: "🔄",
    category: "数据",
    steps: 12,
    status: "运行中",
    runs: 2100,
    successRate: "98.8%",
    avgDuration: "15m 30s",
    tags: ["推荐", "热门"],
    lastRun: "5分钟前",
  },
  {
    id: 4,
    name: "客户服务流程",
    description: "工单自动分类、分配和跟进流程",
    icon: "🎫",
    category: "客服",
    steps: 6,
    status: "已暂停",
    runs: 560,
    successRate: "94.2%",
    avgDuration: "2m 45s",
    tags: [],
    lastRun: "3天前",
  },
  {
    id: 5,
    name: "报告生成流程",
    description: "定时生成业务报告并发送邮件",
    icon: "📊",
    category: "报表",
    steps: 4,
    status: "运行中",
    runs: 320,
    successRate: "100%",
    avgDuration: "8m 10s",
    tags: ["新上线"],
    lastRun: "2小时前",
  },
  {
    id: 6,
    name: "部署发布流程",
    description: "自动化CI/CD部署流程，支持回滚",
    icon: "🚀",
    category: "DevOps",
    steps: 10,
    status: "运行中",
    runs: 780,
    successRate: "96.5%",
    avgDuration: "12m 00s",
    tags: ["推荐"],
    lastRun: "30分钟前",
  },
];

export async function GET() {
  return NextResponse.json({ workflows });
}
